sudo: required

language: python
cache: pip
python:
  - '3.6'

services: docker
install:
  - pip install awscli
  - aws s3 cp s3://buildarchive.countme.codingbyday.com/kubeconfig kubeconfig
  - curl -L https://storage.googleapis.com/kubernetes-helm/helm-v2.8.0-rc.1-linux-amd64.tar.gz -o helm.tgz
  - tar xf helm.tgz --strip 1 linux-amd64/helm
script:
  - docker-compose build
  - export PATH=$HOME/.local/bin:$PATH
  - eval $(aws ecr get-login --no-include-email --region us-west-2)
  - docker tag vctotechevalops_countme:latest 742602405696.dkr.ecr.us-west-2.amazonaws.com/vcto-tech-eval-ops:latest
  - docker push 742602405696.dkr.ecr.us-west-2.amazonaws.com/vcto-tech-eval-ops:latest
  - KUBECONFIG=kubeconfig ./helm init --client-only
  - KUBECONFIG=kubeconfig ./helm dep up ./chart/
  - KUBECONFIG=kubeconfig ./helm upgrade --namespace default --install vcto ./chart/
after_script:
  - rm kubeconfig